protocol: "ICM2O"
train_set: ["Replay_attack", "CASIA_MFSD", "MSU_MFSD"]
test_set:  ["ROSE_Youtu"]

running_name: ""

seed: 998244353

PRETRAINED:
    skip_training: False
    weights_path: "./weights/best/icm2o.pth"

PATH:
    data_folder: "./datasets/"
    output_folder: "./logs/"

SYS:
    num_gpus: 1
    GPUs: "1"
    num_workers: 4
MODEL:
    model_name: "resnet18"
    norm: True
    usebias: False
    image_size: 256
    num_classes: 1

TRAIN:
    pretrained: "imagenet"
    batch_size: 96
    lr: 0.005
    fc_lr_scale: 1
    weight_decay: 0.0005
    momentum: 0.9
    lr_step_size: 40
    lr_gamma: 0.5
    optimizer: "SGD"
    scheduler: "step"
    warming_epochs: 1
    epochs: 150
    loss_func: "bce"
    logit_scale: 12
    rotate: True
    color_jitter: False
    cutout: True
    feat_loss: "supcon"
    lambda_constrast: 0.2

    minimizer: "gac" # gac-fas
    minimizer_warming: 10

    GAC:
        rho: 0.1
        eta: 0.0
        alpha: 0.0002
TEST:
    eval_preq: 5
    test_on_wfas: False
