protocol: "OCM2I"
train_set: ["OULU", "CASIA_MFSD", "MSU_MFSD"]
test_set: ["ROSE_Youtu"]

running_name: ""

seed: 55555

PRETRAINED:
    skip_training: True
    weights_path: "./weights/rose_as_val_best/ocm2i.pth"

PATH:
    data_folder: "./datasets/"
    output_folder: "./logs/"

SYS:
    num_gpus: 1
    GPUs: "1"
    num_workers: 4
MODEL:
    model_name: "resnet18"
    norm: True
    usebias: False
    image_size: 256
    num_classes: 1

TRAIN:
    pretrained: "imagenet"
    batch_size: 96
    lr: 0.01
    fc_lr_scale: 1
    weight_decay: 0.0001
    momentum: 0.9
    lr_step_size: 40
    lr_gamma: 0.5
    optimizer: "SGD"
    scheduler: "step"
    warming_epochs: 1
    epochs: 50
    logit_scale: 16
    rotate: True
    color_jitter: True
    cutout: True
    loss_func: "bce"
    feat_loss: "supcon"
    lambda_constrast: 0.1

    minimizer: "gac"  # "gac-fas"
    minimizer_warming: 10

    GAC:
        rho: 0.1
        alpha: 0.0002
TEST:
    eval_preq: 1
    test_on_wfas: False
